"""empty message

Revision ID: 3_add_housing_units_table
Revises: 2_populate_users_with_base_users
Create Date: 2021-12-01 02:23:11.555694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3_add_housing_units_table'
down_revision = '2_populate_users_with_base_users'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housingunits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_start_date', sa.DateTime(), nullable=True),
    sa.Column('project_completion_date', sa.DateTime(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=False),
    sa.Column('borough', sa.String(), nullable=False),
    sa.Column('postcode', sa.Integer()),
    sa.Column('bbl', sa.BigInteger(), nullable=True),
    sa.Column('bin', sa.Integer(), nullable=True),
    sa.Column('community_board', sa.String(), nullable=True),
    sa.Column('council_district', sa.Integer(), nullable=True),
    sa.Column('census_tract', sa.String(), nullable=True),
    sa.Column('neighborhood_tabulation_area', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude_internal', sa.Float(), nullable=True),
    sa.Column('longitude_internal', sa.Float(), nullable=True),
    sa.Column('building_completion_date', sa.DateTime()),
    sa.Column('reporting_construction_type', sa.String()),
    sa.Column('extended_affordability_status', sa.String(), nullable=True),
    sa.Column('prevailing_wage_status', sa.String(), nullable=True),
    sa.Column('extremely_low_income_units', sa.Integer(), nullable=True),
    sa.Column('very_low_income_units', sa.Integer(), nullable=True),
    sa.Column('low_income_units', sa.Integer(), nullable=True),
    sa.Column('moderate_income_units', sa.Integer(), nullable=True),
    sa.Column('middle_income_units', sa.Integer(), nullable=True),
    sa.Column('other_income_units', sa.Integer(), nullable=True),
    sa.Column('studio_units', sa.Integer(), nullable=True),
    sa.Column('_1_br_units', sa.Integer(), nullable=True),
    sa.Column('_2_br_units', sa.Integer(), nullable=True),
    sa.Column('_3_br_units', sa.Integer(), nullable=True),
    sa.Column('_4_br_units', sa.Integer(), nullable=True),
    sa.Column('_5_br_units', sa.Integer(), nullable=True),
    sa.Column('_6_br_units', sa.Integer(), nullable=True),
    sa.Column('unknown_br_units', sa.Integer(), nullable=True),
    sa.Column('counted_rental_units', sa.Integer(), nullable=True),
    sa.Column('counted_homeownership_units', sa.Integer(), nullable=True),
    sa.Column('all_counted_units', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_housingunits__1_br_units'), 'housingunits', ['_1_br_units'], unique=False)
    op.create_index(op.f('ix_housingunits__2_br_units'), 'housingunits', ['_2_br_units'], unique=False)
    op.create_index(op.f('ix_housingunits__3_br_units'), 'housingunits', ['_3_br_units'], unique=False)
    op.create_index(op.f('ix_housingunits__4_br_units'), 'housingunits', ['_4_br_units'], unique=False)
    op.create_index(op.f('ix_housingunits__5_br_units'), 'housingunits', ['_5_br_units'], unique=False)
    op.create_index(op.f('ix_housingunits__6_br_units'), 'housingunits', ['_6_br_units'], unique=False)
    op.create_index(op.f('ix_housingunits_all_counted_units'), 'housingunits', ['all_counted_units'], unique=False)
    op.create_index(op.f('ix_housingunits_borough'), 'housingunits', ['borough'], unique=False)
    op.create_index(op.f('ix_housingunits_extremely_low_income_units'), 'housingunits', ['extremely_low_income_units'], unique=False)
    op.create_index(op.f('ix_housingunits_low_income_units'), 'housingunits', ['low_income_units'], unique=False)
    op.create_index(op.f('ix_housingunits_middle_income_units'), 'housingunits', ['middle_income_units'], unique=False)
    op.create_index(op.f('ix_housingunits_moderate_income_units'), 'housingunits', ['moderate_income_units'], unique=False)
    op.create_index(op.f('ix_housingunits_other_income_units'), 'housingunits', ['other_income_units'], unique=False)
    op.create_index(op.f('ix_housingunits_postcode'), 'housingunits', ['postcode'], unique=False)
    op.create_index(op.f('ix_housingunits_project_id'), 'housingunits', ['project_id'], unique=False)
    op.create_index(op.f('ix_housingunits_reporting_construction_type'), 'housingunits', ['reporting_construction_type'], unique=False)
    op.create_index(op.f('ix_housingunits_street_name'), 'housingunits', ['street_name'], unique=False)
    op.create_index(op.f('ix_housingunits_studio_units'), 'housingunits', ['studio_units'], unique=False)
    op.create_index(op.f('ix_housingunits_total_units'), 'housingunits', ['total_units'], unique=False)
    op.create_index(op.f('ix_housingunits_unknown_br_units'), 'housingunits', ['unknown_br_units'], unique=False)
    op.create_index(op.f('ix_housingunits_very_low_income_units'), 'housingunits', ['very_low_income_units'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_housingunits_very_low_income_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_unknown_br_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_total_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_studio_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_street_name'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_reporting_construction_type'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_project_id'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_postcode'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_other_income_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_moderate_income_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_middle_income_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_low_income_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_extremely_low_income_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_borough'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits_all_counted_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits__6_br_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits__5_br_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits__4_br_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits__3_br_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits__2_br_units'), table_name='housingunits')
    op.drop_index(op.f('ix_housingunits__1_br_units'), table_name='housingunits')
    op.drop_table('housingunits')
    # ### end Alembic commands ###
