"""empty message

Revision ID: 3_add_hbd_building_table
Revises: 2_populate_users_with_base_users
Create Date: 2021-12-01 02:23:11.555694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3_add_hbd_building_table'
down_revision = '2_populate_users_with_base_users'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hbdbuildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_start_date', sa.DateTime(), nullable=True),
    sa.Column('project_completion_date', sa.DateTime(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=False),
    sa.Column('borough', sa.String(), nullable=False),
    sa.Column('postcode', sa.Integer()),
    sa.Column('bbl', sa.BigInteger(), nullable=True),
    sa.Column('bin', sa.Integer(), nullable=True),
    sa.Column('community_board', sa.String(), nullable=True),
    sa.Column('council_district', sa.Integer(), nullable=True),
    sa.Column('census_tract', sa.String(), nullable=True),
    sa.Column('neighborhood_tabulation_area', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude_internal', sa.Float(), nullable=True),
    sa.Column('longitude_internal', sa.Float(), nullable=True),
    sa.Column('building_completion_date', sa.DateTime()),
    sa.Column('reporting_construction_type', sa.String()),
    sa.Column('extended_affordability_status', sa.String(), nullable=True),
    sa.Column('prevailing_wage_status', sa.String(), nullable=True),
    sa.Column('extremely_low_income_units', sa.Integer(), nullable=True),
    sa.Column('very_low_income_units', sa.Integer(), nullable=True),
    sa.Column('low_income_units', sa.Integer(), nullable=True),
    sa.Column('moderate_income_units', sa.Integer(), nullable=True),
    sa.Column('middle_income_units', sa.Integer(), nullable=True),
    sa.Column('other_income_units', sa.Integer(), nullable=True),
    sa.Column('studio_units', sa.Integer(), nullable=True),
    sa.Column('_1_br_units', sa.Integer(), nullable=True),
    sa.Column('_2_br_units', sa.Integer(), nullable=True),
    sa.Column('_3_br_units', sa.Integer(), nullable=True),
    sa.Column('_4_br_units', sa.Integer(), nullable=True),
    sa.Column('_5_br_units', sa.Integer(), nullable=True),
    sa.Column('_6_br_units', sa.Integer(), nullable=True),
    sa.Column('unknown_br_units', sa.Integer(), nullable=True),
    sa.Column('counted_rental_units', sa.Integer(), nullable=True),
    sa.Column('counted_homeownership_units', sa.Integer(), nullable=True),
    sa.Column('all_counted_units', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_hbdbuildings__1_br_units'), 'hbdbuildings', ['_1_br_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings__2_br_units'), 'hbdbuildings', ['_2_br_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings__3_br_units'), 'hbdbuildings', ['_3_br_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings__4_br_units'), 'hbdbuildings', ['_4_br_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings__5_br_units'), 'hbdbuildings', ['_5_br_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings__6_br_units'), 'hbdbuildings', ['_6_br_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_all_counted_units'), 'hbdbuildings', ['all_counted_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_borough'), 'hbdbuildings', ['borough'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_extremely_low_income_units'), 'hbdbuildings', ['extremely_low_income_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_low_income_units'), 'hbdbuildings', ['low_income_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_middle_income_units'), 'hbdbuildings', ['middle_income_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_moderate_income_units'), 'hbdbuildings', ['moderate_income_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_other_income_units'), 'hbdbuildings', ['other_income_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_postcode'), 'hbdbuildings', ['postcode'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_project_id'), 'hbdbuildings', ['project_id'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_reporting_construction_type'), 'hbdbuildings', ['reporting_construction_type'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_street_name'), 'hbdbuildings', ['street_name'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_studio_units'), 'hbdbuildings', ['studio_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_total_units'), 'hbdbuildings', ['total_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_unknown_br_units'), 'hbdbuildings', ['unknown_br_units'], unique=False)
    op.create_index(op.f('ix_hbdbuildings_very_low_income_units'), 'hbdbuildings', ['very_low_income_units'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hbdbuildings_very_low_income_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_unknown_br_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_total_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_studio_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_street_name'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_reporting_construction_type'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_project_id'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_postcode'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_other_income_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_moderate_income_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_middle_income_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_low_income_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_extremely_low_income_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_borough'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings_all_counted_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings__6_br_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings__5_br_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings__4_br_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings__3_br_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings__2_br_units'), table_name='hbdbuildings')
    op.drop_index(op.f('ix_hbdbuildings__1_br_units'), table_name='hbdbuildings')
    op.drop_table('hbdbuildings')
    # ### end Alembic commands ###
